<?php
	
	include '../conexion.php';

	$fecha = date('d_m_y_H:i:s');

	header('Content-Type: application/vnd.ms-excel; charset=UTF-8');
	header("Content-Disposition: attachment; filename=Cargas Familiares $fecha.xls");
	header("Pragma: no-cache");
	header("Expires: 0");

?>

		<table>

		<?php

			$query = mysqli_query($conection, "SELECT t.`CEDULA` AS `CEDULA REPRESENTANTE`, t.`Nro DE RIF` AS `Nro DE RIF REPRESENTANTE`, t.`PRIMER APELLIDO` AS `PRIMER APELLIDO REPRESENTANTE`, t.`SEGUNDO APELLIDO` AS `SEGUNDO APELLIDO REPRESENTANTE`, t.`PRIMER NOMBRE` AS `PRIMER NOMBRE REPRESENTANTE`, t.`SEGUNDO NOMBRE` AS `SEGUNDO NOMBRE REPRESENTANTE`, t.`FECHA DE NACIMIENTO` AS `FECHA DE NACIMIENTO REPRESENTANTE`, t.`CIUDAD` AS `CIUDAD REPRESENTANTE`, t.`NACIONALIDAD` AS `NACIONALIDAD REPRESENTANTE`, t.`DOBLE NACIONALIDAD` AS `DOBLE NACIONALIDAD REPRESENTANTE`, t.`FECHA DE NACIONALIDAD` AS `FECHA NACIONALIDAD REPRESENTANTE`, t.`CODIGO CARNET PATRIA` AS `CODIGO CARNET PATRIA REPRESENTANTE`, t.`SERIAL CARNET PATRIA` AS `SERIAL CARNET PATRIA REPRESENTANTE`, t.`GACETA Nro` AS `GACETA Nro REPRESENTANTE`, t.`PADRE/MADRE` AS `PADRE/MADRE REPRESENTANTE`, t.`SEXO` AS `SEXO REPRESENTANTE`, t.`ESTADO CIVIL` AS `ESTADO CIVIL REPRESENTANTE`, t.`POSEE ALGUNA DISCAPACIDAD` AS `POSEE ALGUNA DISCAPACIDAD REPRESENTANTE`, t.`ESPECIFIQUE` AS `ESPECIFIQUE REPRESENTANTE`, t.`POSEE ALGUNA ENFERMEDAD` AS `POSEE ALGUNA ENFERMEDAD REPRESENTANTE`, t.`ESPECIFIQUE ENFERMEDAD` AS `ESPECIFIQUE ENFERMEDAD REPRESENTANTE`, t.`TOMA ALGUN MEDICAMENTO` AS `TOMA ALGUN MEDICAMENTO REPRESENTANTE`, t.`ENTIDAD BANCARIA` AS `ENTIDAD BANCARIA REPRESENTANTE`, t.`CUENTA NOMINA` AS `CUENTA NOMINA REPRESENTANTE`, t.`FORMA DE PAGO` AS `FORMA DE PAGO REPRESENTANTE`, t.`DIRECCION DE HABITACION` AS `DIRECCION DE HABITACION REPRESENTANTE`, t.`MUNICIPIO` AS `MUNICIPIO REPRESENTANTE`, t.`ESTADO` AS `ESTADO REPRESENTANTE`, t.`CENTRO DE VOTACION` AS `CENTRO DE VOTACION REPRESENTANTE`, t.`PERTENECE A UNA ORGANIZACION SOCIAL` AS `PERTENECE A UNA ORGANIZACION SOCIAL REPRESENTANTE`, t.`CUAL ORGANIZACION SOCIAL` AS `CUAL ORGANIZACION SOCIAL REPRESENTANTE`, t.`PERTENECE AL CONSEJO COMUNAL DE SU COMUNIDAD` AS `PERTENECE AL CONSEJO COMUNAL DE SU COMUNIDAD REPRESENTANTE`, t.`TELEFONO FIJO DE HABITACION` AS `TELEFONO FIJO DE HABITACION REPRESENTANTE`, t.`TELEFONO MOVIL` AS `TELEFONO MOVIL REPRESENTANTE`, t.`TELEFONO DE OFICINA` AS `TELEFONO DE OFICINA REPRESENTANTE`, t.`CORREO ELECTRONICO` AS `CORREO ELECTRONICO REPRESENTANTE`, t.`TIPO DE VIVIENDA` AS `TIPO DE VIVIENDA REPRESENTANTE`, t.`TENDENCIA DE VIVIENDA` AS `TENDENCIA DE VIVIENDA REPRESENTANTE`, t.`MANEJA` AS `MANEJA REPRESENTANTE`, t.`GRADO DE LICENCIA` AS `GRADO DE LICENCIA REPRESENTANTE`, t.`GRUPO SANGUINEO` AS `GRUPO SANGUINEO REPRESENTANTE`, t.`ESTATURA` AS `ESTATURA REPRESENTANTE`, t.`PESO` AS `PESO REPRESENTANTE`, t.`PANTALON` AS `PANTALON REPRESENTANTE`, t.`CAMISA` AS `CAMISA REPRESENTANTE`, t.`ZAPATO` AS `ZAPATO REPRESENTANTE`, t.`MANO DOMINANTE` AS `MANO DOMINANTE REPRESENTANTE`, t.`NIVEL EDUCATIVO ESTUDIOS` AS `NIVEL EDUCATIVO ESTUDIOS REPRESENTANTE`, t.`ESPECIALIDAD O DOCTORADO` AS `ESPECIALIDAD O DOCTORADO REPRESENTANTE`, t.`PROFESION` AS `PROFESION REPRESENTANTE`, t.`DEPENDENCIA ADSCRITA NOMINALMENTE` AS `DEPENDENCIA ADSCRITA NOMINALMENTE REPRESENTANTE`, t.`DEPENDENCIA DONDE TRABAJA FISICAMENTE` AS `DEPENDENCIA DONDE TRABAJA FISICAMENTE REPRESENTANTE`, t.`UBICACION ADMINISTRATIVA` AS `UBICACION ADMINISTRATIVA REPRESENTANTE`, t.`UBICACION FISICA` AS `UBICACION FISICA REPRESENTANTE`, t.`DIRECCION EXACTA DEL LUGAR DE TRABAJO` AS `DIRECCION EXACTA DEL LUGAR DE TRABAJO REPRESENTANTE`, t.`CORREO ELECTRONICO DEL LUGAR DE TRABAJO` AS `CORREO ELECTRONICO DEL LUGAR DE TRABAJO REPRESENTANTE`, t.`TELEFONO DE LA OFICINA` AS `TELEFONO DE LA OFICINA REPRESENTANTE`, t.`CODIGO NOMINAL` AS `CODIGO NOMINAL REPRESENTANTE`, t.`CARGO` AS `CARGO REPRESENTANTE`, t.`TIPO DE PERSONAL` AS `TIPO DE PERSONAL REPRESENTANTE`, t.`TIPO DE TRABAJADOR` AS `TIPO DE TRABAJADOR REPRESENTANTE`, t.`OCUPACION` AS `OCUPACION REPRESENTANTE`, t.`CARGA HORARIA` AS `CARGA HORARIA REPRESENTANTE`, t.`JORNADA DIARIA` AS `JORNADA DIARIA REPRESENTANTE`, t.`GUARDIAS NOCTURNAS` AS `GUARDIAS NOCTURNAS REPRESENTANTE`, t.`ASIC` AS `ASIC REPRESENTANTE`, t.`ORGANISMO DE ADSCRIPCION` AS `ORGANISMO DE ADSCRIPCION REPRESENTANTE`, t.`BREVE DESCRIPCION DEL CARGO` AS `BREVE DESCRIPCION DEL CARGO REPRESENTANTE`, t.`FECHA DE INGRESO` AS `FECHA DE INGRESO REPRESENTANTE`, t.`ASAP ANTES DEL INGRESO D.S.M` AS `ASAP ANTES DEL INGRESO D.S.M REPRESENTANTE`, t.`DECLARACION JURADA DE PATRIMONIO` AS `DECLARACION JURADA DE PATRIMONIO REPRESENTANTE`, t.`OBSERVACIONES` AS `OBSERVACIONES REPRESENTANTE`, c.`ID CARGA FAMILIAR`,c.`ID`,c.`PRIMER APELLIDO`,c.`SEGUNDO APELLIDO`,c.`PRIMER NOMBRE`,c.`SEGUNDO NOMBRE`,c.`CEDULA`,c.`PARENTESCO`,c.`FECHA DE NACIMIENTO`,c.`NIVEL DE ESTUDIO`,c.`POSEE ALGUNA CONDICION ESPECIAL`, c.`OBSERVACIONES` FROM `carga familiar` c INNER JOIN `trabajadores` t WHERE t.`ID` = c.`ID` ORDER BY `ID` ASC;");
			mysqli_close($conection);
			if($query){
				$result = mysqli_num_rows($query);
			}else{
				$result = 0;
			}

			if($result > 0){

				while ($data = mysqli_fetch_array($query)) {

		?>
			
			<tr>

				<th>

					REPRESENTANTE:

				</th>

			</tr>

			<tr>
				
				<th>CEDULA</th>
				<th>NRO DE RIF</th>
				<th>PRIMER APELLIDO</th>
				<th>SEGUNDO APELLIDO</th>
				<th>PRIMER NOMBRE</th>
				<th>SEGUNDO NOMBRE</th>
				<th>FECHA DE NACIMIENTO</th>
				<th>LUGAR DE NACIMIENTO</th>
				<th>NACIONALIDAD</th>
				<th>DOBLE NACIONALIDAD</th>
				<th>FECHA DE NACIONALIDAD</th>
				<th>CODIGO CARNET PATRIA</th>
				<th>SERIAL CARNET PATRIA</th>
				<th>GACETA NRO</th>
				<th>TIENE HIJOS</th>
				<th>SEXO</th>
				<th>ESTADO CIVIL</th>
				<th>POSEE ALGUNA DISCAPACIDAD</th>
				<th>ESPECIFIQUE DISCAPACIDAD</th>
				<th>POSEE ALGUNA ENFERMEDAD</th>
				<th>ESPECIFIQUE ENFERMEDAD</th>
				<th>TOMA ALGUN MEDICAMENTO</th>
				<th>ENTIDAD BANCARIA</th>
				<th>CUENTA NOMINA</th>
				<th>FORMA DE PAGO</th>
				<th>DIRECCION DE HABITACION</th>
				<th>MUNICIPIO</th>
				<th>ESTADO</th>
				<th>CENTRO DE VOTACION</th>
				<th>PERTENECE A UNA ORGANIZACION SOCIAL</th>
				<th>CUAL ORGANIZACION SOCIAL</th>	
				<th>PERTENECE AL CONSEJO COMUNAL DE SU COMUNIDAD</th>	
				<th>TELEFONO FIJO DE HABITACION</th>
				<th>TELEFONO MOVIL</th>
				<th>TELEFONO DE OFICINA</th>
				<th>CORREO ELECTRONICO</th>
				<th>TIPO DE VIVIENDA</th>
				<th>TENDENCIA DE VIVIENDA</th>
				<th>MANEJA</th>
				<th>GRADO DE LICENCIA</th>
				<th>GRUPO SANGUINEO</th>
				<th>ESTATURA (M)</th>
				<th>PESO (Kg)</th>
				<th>PANTALON</th>
				<th>CAMISA</th>
				<th>ZAPATO</th>
				<th>MANO DOMINANTE</th>
				<th>NIVEL EDUCATIVO ESTUDIOS</th>
				<th>ESPECIALIDAD O DOCTORADO</th>
				<th>PROFESION</th>
				<th>DEPENDENCIA ADSCRITA NOMINALMENTE</th>
				<th>DEPENDENCIA DONDE TRABAJA FISICAMENTE</th>
				<th>UBICACION ADMINISTRATIVA</th>
				<th>UBICACION FISICA</th>
				<th>DIRECCION EXACTA DEL LUGAR DE TRABAJO</th>
				<th>CORREO ELECTRONICO DEL LUGAR DE TRABAJO</th>
				<th>TELEFONO DE LA OFICINA</th>
				<th>CODIGO DE NOMINA</th>
				<th>CARGO</th>
				<th>TIPO DE PERSONAL</th>
				<th>TIPO DE TRABAJADOR</th>
				<th>OCUPACION</th>
				<th>CARGA HORARIA</th>
				<th>JORNADA DIARIA</th>
				<th>GUARDIAS NOCTURNAS</th>
				<th>ASIC</th>
				<th>ORGANISMO DE ADSCRIPCION</th>
				<th>BREVE DESCRIPCION DEL CARGO</th>
				<th>FECHA DE INGRESO</th>
				<th>ASAP ANTES DEL INGRESO D.S.M</th>
				<th>DECLARACION JURADA DE PATRIMONIO</th>
				<th>OBSERVACIONES</th>

			</tr>

			<tr>

				<td><?php echo $data['CEDULA REPRESENTANTE']; ?></td>
				<td><?php echo $data['Nro DE RIF REPRESENTANTE']; ?></td>
				<td><?php echo $data['PRIMER APELLIDO REPRESENTANTE']; ?></td>
				<td><?php echo $data['SEGUNDO APELLIDO REPRESENTANTE']; ?></td>
				<td><?php echo $data['PRIMER NOMBRE REPRESENTANTE']; ?></td>
				<td><?php echo $data['SEGUNDO NOMBRE REPRESENTANTE']; ?></td>
				<td><?php echo $data['FECHA DE NACIMIENTO REPRESENTANTE'] ?></td>
				<td><?php echo $data['CIUDAD REPRESENTANTE']; ?></td>
				<td><?php echo $data['NACIONALIDAD REPRESENTANTE']; ?></td>
				<td><?php echo $data['DOBLE NACIONALIDAD REPRESENTANTE']; ?></td>
				<td><?php echo $data['FECHA NACIONALIDAD REPRESENTANTE']; ?></td>
				<td><?php echo $data['CODIGO CARNET PATRIA REPRESENTANTE']; ?></td>
				<td><?php echo $data['SERIAL CARNET PATRIA REPRESENTANTE']; ?></td>
				<td><?php echo $data['GACETA Nro REPRESENTANTE']; ?></td>
				<td><?php echo $data['PADRE/MADRE REPRESENTANTE'] ?></td>
				<td><?php echo $data['SEXO REPRESENTANTE']; ?></td>
				<td><?php echo $data['ESTADO CIVIL REPRESENTANTE'] ?></td>
				<td><?php echo $data['POSEE ALGUNA DISCAPACIDAD REPRESENTANTE']; ?></td>
				<td><?php echo $data['ESPECIFIQUE REPRESENTANTE']; ?></td>
				<td><?php echo $data['POSEE ALGUNA ENFERMEDAD REPRESENTANTE']; ?></td>
				<td><?php echo $data['ESPECIFIQUE ENFERMEDAD REPRESENTANTE']; ?></td>
				<td><?php echo $data['TOMA ALGUN MEDICAMENTO REPRESENTANTE']; ?></td>
				<td><?php echo $data['ENTIDAD BANCARIA REPRESENTANTE']; ?></td>
				<td><?php echo $data['CUENTA NOMINA REPRESENTANTE']; ?></td>
				<td><?php echo $data['FORMA DE PAGO REPRESENTANTE']; ?></td>
				<td><?php echo $data['DIRECCION DE HABITACION REPRESENTANTE']; ?></td>
				<td><?php echo $data['MUNICIPIO REPRESENTANTE']; ?></td>
				<td><?php echo $data['ESTADO REPRESENTANTE']; ?></td>
				<td><?php echo $data['CENTRO DE VOTACION REPRESENTANTE']; ?></td>
				<td><?php echo $data['PERTENECE A UNA ORGANIZACION SOCIAL REPRESENTANTE']; ?></td>
				<td><?php echo $data['CUAL ORGANIZACION SOCIAL REPRESENTANTE']; ?></td>
				<td><?php echo $data['PERTENECE AL CONSEJO COMUNAL DE SU COMUNIDAD REPRESENTANTE']; ?></td>
				<td><?php echo $data['TELEFONO FIJO DE HABITACION REPRESENTANTE']; ?></td>
				<td><?php echo $data['TELEFONO MOVIL REPRESENTANTE']; ?></td>
				<td><?php echo $data['TELEFONO DE OFICINA REPRESENTANTE']; ?></td>
				<td><?php echo $data['CORREO ELECTRONICO REPRESENTANTE']; ?></td>
				<td><?php echo $data['TIPO DE VIVIENDA REPRESENTANTE']; ?></td>
				<td><?php echo $data['TENDENCIA DE VIVIENDA REPRESENTANTE']; ?></td>
				<td><?php echo $data['MANEJA REPRESENTANTE']; ?></td>
				<td><?php echo $data['GRADO DE LICENCIA REPRESENTANTE']; ?></td>
				<td><?php echo $data['GRUPO SANGUINEO REPRESENTANTE']; ?></td>
				<td><?php echo $data['ESTATURA REPRESENTANTE']; ?></td>
				<td><?php echo $data['PESO REPRESENTANTE']; ?></td>
				<td><?php echo $data['PANTALON REPRESENTANTE']; ?></td>
				<td><?php echo $data['CAMISA REPRESENTANTE']; ?></td>
				<td><?php echo $data['ZAPATO REPRESENTANTE']; ?></td>
				<td><?php echo $data['MANO DOMINANTE REPRESENTANTE']; ?></td>
				<td><?php echo $data['NIVEL EDUCATIVO ESTUDIOS REPRESENTANTE']; ?></td>
				<td><?php echo $data['ESPECIALIDAD O DOCTORADO REPRESENTANTE']; ?></td>
				<td><?php echo $data['PROFESION REPRESENTANTE']; ?></td>
				<td><?php echo $data['DEPENDENCIA ADSCRITA NOMINALMENTE REPRESENTANTE']; ?></td>
				<td><?php echo $data['DEPENDENCIA DONDE TRABAJA FISICAMENTE REPRESENTANTE']; ?></td>
				<td><?php echo $data['UBICACION ADMINISTRATIVA REPRESENTANTE']; ?></td>
				<td><?php echo $data['UBICACION FISICA REPRESENTANTE']; ?></td>
				<td><?php echo $data['DIRECCION EXACTA DEL LUGAR DE TRABAJO REPRESENTANTE']; ?></td>
				<td><?php echo $data['CORREO ELECTRONICO DEL LUGAR DE TRABAJO REPRESENTANTE']; ?></td>
				<td><?php echo $data['TELEFONO DE LA OFICINA REPRESENTANTE']; ?></td>
				<td><?php echo $data['CODIGO NOMINAL REPRESENTANTE']; ?></td>
				<td><?php echo $data['CARGO REPRESENTANTE']; ?></td>
				<td><?php echo $data['TIPO DE PERSONAL REPRESENTANTE']; ?></td>
				<td><?php echo $data['TIPO DE TRABAJADOR REPRESENTANTE']; ?></td>
				<td><?php echo $data['OCUPACION REPRESENTANTE']; ?></td>
				<td><?php echo $data['CARGA HORARIA REPRESENTANTE']; ?></td>
				<td><?php echo $data['JORNADA DIARIA REPRESENTANTE']; ?></td>
				<td><?php echo $data['GUARDIAS NOCTURNAS REPRESENTANTE']; ?></td>
				<td><?php echo $data['ASIC REPRESENTANTE']; ?></td>
				<td><?php echo $data['ORGANISMO DE ADSCRIPCION REPRESENTANTE']; ?></td>
				<td><?php echo $data['BREVE DESCRIPCION DEL CARGO REPRESENTANTE']; ?></td>
				<td><?php echo $data['FECHA DE INGRESO REPRESENTANTE']; ?></td>
				<td><?php echo $data['ASAP ANTES DEL INGRESO D.S.M REPRESENTANTE']; ?></td>
				<td><?php echo $data['DECLARACION JURADA DE PATRIMONIO REPRESENTANTE']; ?></td>
				<td><?php echo $data['OBSERVACIONES REPRESENTANTE']; ?></td>

			</tr>

			<tr>

				<th>

					CARGA FAMILIAR:

				</th>

			</tr>

			<tr>
				
				<th>PRIMER APELLIDO</th>
				<th>SEGUNDO APELLIDO</th>
				<th>PRIMER NOMBRE</th>
				<th>SEGUNDO NOMBRE</th>
				<th>CEDULA</th>
				<th>PARENTESCO</th>
				<th>FECHA DE NACIMIENTO</th>
				<th>NIVEL DE ESTUDIO</th>
				<th>CONDICION ESPECIAL</th>
				<th>OBSERVACIONES</th>

			</tr>

			<tr>
				
				<td><?php echo $data['PRIMER APELLIDO'] ?></td>
				<td><?php echo $data['SEGUNDO APELLIDO'] ?></td>
				<td><?php echo $data['PRIMER NOMBRE'] ?></td>
				<td><?php echo $data['SEGUNDO NOMBRE'] ?></td>
				<td><?php echo $data['CEDULA'] ?></td>
				<td><?php echo $data['PARENTESCO'] ?></td>
				<td><?php echo $data['FECHA DE NACIMIENTO'] ?></td>
				<td><?php echo $data['NIVEL DE ESTUDIO'] ?></td>
				<td><?php echo $data['POSEE ALGUNA CONDICION ESPECIAL'] ?></td>
				<td><?php echo $data['OBSERVACIONES'] ?></td>

			</tr>

		<?php

				}

			}

		?>

		</table>